/**
 * @file extended_euclidean.h
 * @brief Extended Euclidean Algorithm (EEA) utilities.
 *
 * The EEA computes the greatest common divisor of two integers together with
 * Bézout coefficients.  DioSolver represents the computation as a `calist`
 * of `EEAR` rows.  The final row has remainder zero; the preceding row contains
 * the greatest common divisor and the coefficients for the corresponding
 * Bézout combination.
 */

#ifndef DIOSOLVER_EXTENDED_EUCLIDEAN_H
#define DIOSOLVER_EXTENDED_EUCLIDEAN_H

#include <calist.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Represents one row in an EEA table.
 *
 * For a table generated by `eea_table(a, b)`, `x` and `y` are the Bézout
 * coefficients for the two initial absolute values, `r` is the current
 * remainder, and `q` is the quotient used to produce the row.  The initial
 * rows have a quotient of zero.  The initial absolute values are ordered from
 * larger to smaller, so the coefficients are not necessarily associated with
 * the original argument order.
 */
typedef struct EEAR {
    int x; /**< Bézout coefficient for the first initial remainder. */
    int y; /**< Bézout coefficient for the second initial remainder. */
    int r; /**< Current remainder. */
    int q; /**< Quotient used to produce this row; zero for initial rows. */
} EEAR;

/**
 * Creates an EEA row with specified values.
 *
 * This constructor does not validate the relationship between the row's
 * coefficients, remainder, or quotient.
 *
 * @param x Bézout coefficient for the first initial remainder.
 * @param y Bézout coefficient for the second initial remainder.
 * @param r Current remainder.
 * @param q Quotient used to produce the row.
 * @return An initialized `EEAR`.
 */
EEAR make_eear(int x, int y, int r, int q);

/**
 * Checks whether two EEA rows have identical fields.
 * 
 * @param r1 The first EEAR.
 * @param r2 The second EEAR.
 * @return `true` if all fields match; otherwise, `false`.
 */
bool equal_eear(EEAR r1, EEAR r2);

/**
 * A `calist` whose elements are `EEAR` rows representing an EEA table.
 *
 * Functions that return an `EEA_Table *` allocate the table dynamically.  The
 * caller owns the table and must release it with `calist_destroy()` when it is
 * no longer needed.
 */
typedef calist EEA_Table;

/**
 * Generates the EEA table for two integers.
 *
 * The table begins with the absolute values of `a` and `b`, ordered from
 * larger to smaller, and ends with a zero-remainder row.  The second-to-last
 * row therefore contains `gcd(a, b)` and its Bézout coefficients.  The
 * returned table deeply copies each row and does not reference the input
 * values.  The caller owns the table and must call `calist_destroy()` after
 * use.
 * 
 * @param a The first integer.
 * @param b The second integer.
 * @return A dynamically allocated `EEA_Table *` containing the EEA rows for
 *         `a` and `b`.
 */
EEA_Table *eea_table(int a, int b);

/**
 * Checks whether two EEA tables have identical sizes and rows.
 *
 * The tables are read but not modified or freed.
 * 
 * @param t1 The first EEA table.
 * @param t2 The second EEA table.
 * @return `true` if the tables match; otherwise, `false`.
 */
bool equal_eea_table(const EEA_Table *t1, const EEA_Table *t2);

/**
 * Computes the second-to-last row of an EEA table without allocating a
 * `calist`.
 *
 * The returned row has remainder `gcd(a, b)` and contains the corresponding
 * Bézout coefficients.  When both inputs are zero, the returned remainder is
 * zero.
 * 
 * @param a The first integer.
 * @param b The second integer.
 * @return The second-to-last `EEAR` row for `a` and `b`.
 */
EEAR eea_2nd_last_row(int a, int b);

/**
 * Computes the non-negative greatest common divisor (GCD) of two integers.
 *
 * The result is `gcd(abs(a), abs(b))`; `eea_gcd(0, 0)` returns zero.
 * 
 * @param a The first integer.
 * @param b The second integer.
 * @return The non-negative GCD of `a` and `b`.
 */
int eea_gcd(int a, int b);

/**
 * Extracts the GCD from the second-to-last row of an EEA table.
 *
 * `table` must contain the rows returned by `eea_table()`, including its
 * terminal zero-remainder row.  This function only reads the table; ownership
 * remains with the caller.  The table must contain at least two rows.
 * 
 * @param table The EEA table containing the computation steps.
 * @return The GCD stored in the table's second-to-last row.
 */
int eea_gcd_table(const EEA_Table *table);

/**
 * Extracts a GCD from an EEA row.
 *
 * For the row to contain the GCD, it must be the second-to-last row of a
 * table generated by `eea_table()`; this function simply returns `row.r` and
 * does not validate the row.
 * 
 * @param row An EEA row, normally the second-to-last row of a table.
 * @return `row.r`.
 */
int eea_gcd_row(EEAR row);

#ifdef __cplusplus
}
#endif

#endif
